//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sequencer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sequencer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a a&apos;s a-1 a-z aa aaa aaaa aaron ab aback abacus abase abash abate abbey abbot abbr abby abc abc&apos;s abcd abduct abdul abe abed abel abet abhor abide ablaze able abm abner aboard abode abort about above abram absent absorb abuse abut abyss ac ac/dc accept accuse ace aces ache ached aches achoo achy acid acidic acids acme acne acorn acquit acre acres acrid act acted actor acts acute ad ada adage adagio adair adam adams adapt add added adder addict addle adds adele adept adieu adios adjust adler admit ado adobe  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string bealeDiceware {
            get {
                return ResourceManager.GetString("bealeDiceware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap delete_24 {
            get {
                object obj = ResourceManager.GetObject("delete_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a a&amp;p a&apos;s aa aaa aaaa aaron ab aba ababa aback abase abash abate abbas abbe abbey abbot abbott abc abe abed abel abet abide abject ablaze able abner abo abode abort about above abrade abram absorb abuse abut abyss ac acadia accra accrue ace acetic ache acid acidic acm acme acorn acre acrid act acton actor acts acuity acute ad ada adage adagio adair adam adams adapt add added addict addis addle adele aden adept adieu adjust adler admit admix ado adobe adonis adopt adore adorn adult advent advert advise ae ae [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string diceware {
            get {
                return ResourceManager.GetString("diceware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap down_32 {
            get {
                object obj = ResourceManager.GetObject("down_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap gear_32 {
            get {
                object obj = ResourceManager.GetObject("gear_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_add {
            get {
                object obj = ResourceManager.GetObject("icon-add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a abandon abandoned abandoning abandons abilities ability able abler ablest about above abroad absence absences absolutely abuse abused abuses abusing academic academics accept accepted accepting accepts access accessed accesses accessing accident accidents accommodation accommodations accompanied accompanies accompany accompanying accord accorded according accords account accounted accounting accounts accuse accused accuses accusing achieve achieved achievement achievements achieves achieving acknowledge a [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ngsl {
            get {
                return ResourceManager.GetString("ngsl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pencil_32 {
            get {
                object obj = ResourceManager.GetObject("pencil_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a abandon ability able abortion about about above above abroad absence absolute absolutely absorb abstract abuse abuse academic accelerate accent accept acceptable acceptance access access accessible accident accommodate accompany accomplish accomplishment according account account accountability accounting accuracy accurate accurately accusation accuse achieve achievement acid acknowledge acquire acquisition across across act act action active actively activist activity actor actress actual actually ad ada [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string top5k {
            get {
                return ResourceManager.GetString("top5k", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap up_32 {
            get {
                object obj = ResourceManager.GetObject("up_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
